// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appglobal;

namespace wasco_q2.models.migrations
{
    [DbContext(typeof(login_db))]
    partial class login_dbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("appglobal.m_user", b =>
                {
                    b.Property<int>("m_user_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("full_name");

                    b.Property<string>("password");

                    b.HasKey("m_user_id");

                    b.ToTable("m_user");
                });

            modelBuilder.Entity("appglobal.t_login_history", b =>
                {
                    b.Property<int>("t_login_history_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("login_time");

                    b.Property<DateTime>("logout_time");

                    b.Property<int>("m_user_id");

                    b.HasKey("t_login_history_id");

                    b.HasIndex("m_user_id");

                    b.ToTable("t_login_history");
                });

            modelBuilder.Entity("appglobal.t_login_history", b =>
                {
                    b.HasOne("appglobal.m_user", "m_user")
                        .WithMany("t_login_history")
                        .HasForeignKey("m_user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
